server:
  port: 8080

spring:
  application:
    name: jspj-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.144:3306/jspj?useSSL=false&serverTimezone=UTC
    username: root
    password: Baydi285396.
  data:
    redis:
      host: 192.168.101.144
      port: 6379
      password: 1234
      database: 2
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
mybatis-plus:
  type-aliases-package: com.lh.jspj.entity # 别名扫描包
logging:
  level:
    com.lh.jspj: debug


